### ISSUE TITLE
Video plays upside down

### ISSUE THREAD

**Issue by rajpa** [lukemadera/meteor-video-capture#2]
Hi @lukemadera thank you for the package! the video capture opens up the mobile camera app and records the video. when it plays back, it is upside down. this happens only on the mobile. it works well on the desktop. any hints on how i can solve this will help a lot!

thanks/rajpa

**Comment by lukemadera** [comment]
You're welcome. I've seen that with picture, e.g. `MeteorCamera.getPicture({ correctOrientation: true }` but I haven't seen this issue with video so unfortunately I'm not sure how to help with that one! If you do figure it out, please share!

**Comment by rajpa** [comment]
Works correctly with later versions of cordova/meteor.
